# this file contains prompts for paraphraser


def paraphrase_text_prompts(text):
    return f"""Paraphrase the given text: 
    ###
    Text: The iPhone was first released in 2007, but at the dawn of the decade it was still a relatively niche product, confined to one wireless carrier and targeted at the early technology adopter. Now it’s a much bigger deal — in the first calendar quarter of 2010, Apple sold 8.7 million iPhones. In the first quarter of 2018, Apple sold 47 million iPhones. The iPhone has also propelled Apple. In the last 10 years, Apple has gone from a large computer company with a profitable side business in MP3 players to a $1 trillion megacorp with operations around the globe and 137,000 full-time employees. The iPhone became intertwined in our lives because it replaced so many other devices.
    Paraphrased text: Even though the iPhone was first introduced in 2007 and was only available through one wireless carrier at the beginning of the decade, it was still considered a relatively niche product aimed at early adopters of technology. These days, it's much bigger news: 8.7 million iPhones were sold by Apple in the first quarter of 2010. Apple sold 47 million iPhones in the first quarter of 2018. Apple has also benefited from the iPhone. Over the past ten years, Apple has grown from a modest computer company with a profitable side business selling MP3 players to a $1 trillion megacorporation with 137,000 full-time employees and operations all over the world. Because it replaced so many other devices, the iPhone became ingrained in our daily lives.
    ###
    Text: Global warming has presented another issue called climate change. Sometimes these phrases are used interchangeably, however, they are different. Climate change refers to changes in weather patterns and growing seasons around the world. It also refers to sea level rise caused by the expansion of warmer seas and melting ice sheets and glaciers. Global warming causes climate change, which poses a serious threat to life on Earth in the forms of widespread flooding and extreme weather. Scientists continue to study global warming and its impact on Earth.
    Paraphrased text: Climate change is a new problem brought on by global warming. Although these terms are occasionally used synonymously, they have different meanings. The term "climate change" describes modifications to global growing seasons and weather patterns. It also describes the rise in sea level brought on by the melting of glaciers and ice sheets and the expansion of warmer oceans. Climate change, a result of global warming, threatens life as we know it by bringing extreme weather patterns and widespread flooding. Researchers are still looking into the effects of global warming on Earth.
    ###
    Text: The great challenge in chemistry is the development of a coherent explanation of the complex behaviour of materials, why they appear as they do, what gives them their enduring properties, and how interactions among different substances can bring about the formation of new substances and the destruction of old ones. From the earliest attempts to understand the material world in rational terms, chemists have struggled to develop theories of matter that satisfactorily explain both permanence and change. The ordered assembly of indestructible atoms into small and large molecules, or extended networks of intermingled atoms, is generally accepted as the basis of permanence, while the reorganization of atoms or molecules into different arrangements lies behind theories of change. 
    Paraphrased text: Developing a logical explanation for the complex behaviour of materials, their appearance, their enduring properties, and how interactions between different substances can result in the formation of new substances and the destruction of old ones is the great challenge of chemistry. Chemists have battled to create theories of matter that adequately explain both permanence and change since the first attempts to rationally comprehend the material world. Theories of change are based on the reorganisation of atoms or molecules into different arrangements, whereas the ordered assembly of indestructible atoms into small and large molecules, or extended networks of intermingled atoms, is generally accepted as the basis of permanence. 
    ###
    Text: {text}
    Paraphrased text: """